// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: replikacija.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// To bomo serializirali vsak event v storage.
type LogEntry struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EntryId   uint64                 `protobuf:"varint,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// To je dejanska operacija (npr. post, update, delete, like) pri nas kot OP_x.
	Payload       []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_replikacija_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_replikacija_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_replikacija_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetEntryId() uint64 {
	if x != nil {
		return x.EntryId
	}
	return 0
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ForwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *LogEntry              `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardRequest) Reset() {
	*x = ForwardRequest{}
	mi := &file_replikacija_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequest) ProtoMessage() {}

func (x *ForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replikacija_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequest.ProtoReflect.Descriptor instead.
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return file_replikacija_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardRequest) GetEntry() *LogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type ForwardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardResponse) Reset() {
	*x = ForwardResponse{}
	mi := &file_replikacija_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardResponse) ProtoMessage() {}

func (x *ForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_replikacija_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardResponse.ProtoReflect.Descriptor instead.
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return file_replikacija_proto_rawDescGZIP(), []int{2}
}

func (x *ForwardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CommitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Do katerega entry_id je vse varno replicirano.
	CommittedEntryId uint64 `protobuf:"varint,1,opt,name=committed_entry_id,json=committedEntryId,proto3" json:"committed_entry_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_replikacija_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replikacija_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_replikacija_proto_rawDescGZIP(), []int{3}
}

func (x *CommitRequest) GetCommittedEntryId() uint64 {
	if x != nil {
		return x.CommittedEntryId
	}
	return 0
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_replikacija_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_replikacija_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_replikacija_proto_rawDescGZIP(), []int{4}
}

func (x *CommitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Zadnji entry_id, ki ga ima ta server.
	LastKnownEntryId uint64 `protobuf:"varint,1,opt,name=last_known_entry_id,json=lastKnownEntryId,proto3" json:"last_known_entry_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_replikacija_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replikacija_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_replikacija_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRequest) GetLastKnownEntryId() uint64 {
	if x != nil {
		return x.LastKnownEntryId
	}
	return 0
}

type UpdateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MissingEntries []*LogEntry            `protobuf:"bytes,1,rep,name=missing_entries,json=missingEntries,proto3" json:"missing_entries,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_replikacija_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_replikacija_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_replikacija_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateResponse) GetMissingEntries() []*LogEntry {
	if x != nil {
		return x.MissingEntries
	}
	return nil
}

var File_replikacija_proto protoreflect.FileDescriptor

const file_replikacija_proto_rawDesc = "" +
	"\n" +
	"\x11replikacija.proto\x12\vreplikacija\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"y\n" +
	"\bLogEntry\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\x04R\aentryId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"=\n" +
	"\x0eForwardRequest\x12+\n" +
	"\x05entry\x18\x01 \x01(\v2\x15.replikacija.LogEntryR\x05entry\"+\n" +
	"\x0fForwardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"=\n" +
	"\rCommitRequest\x12,\n" +
	"\x12committed_entry_id\x18\x01 \x01(\x04R\x10committedEntryId\"*\n" +
	"\x0eCommitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\">\n" +
	"\rUpdateRequest\x12-\n" +
	"\x13last_known_entry_id\x18\x01 \x01(\x04R\x10lastKnownEntryId\"P\n" +
	"\x0eUpdateResponse\x12>\n" +
	"\x0fmissing_entries\x18\x01 \x03(\v2\x15.replikacija.LogEntryR\x0emissingEntries2\xe0\x01\n" +
	"\x12ReplicationService\x12D\n" +
	"\aForward\x12\x1b.replikacija.ForwardRequest\x1a\x1c.replikacija.ForwardResponse\x12A\n" +
	"\x06Commit\x12\x1a.replikacija.CommitRequest\x1a\x1b.replikacija.CommitResponse\x12A\n" +
	"\x06Update\x12\x1a.replikacija.UpdateRequest\x1a\x1b.replikacija.UpdateResponseB8Z6github.com/FedjaMocnik/razpravljalnica/pkgs/private/pbb\x06proto3"

var (
	file_replikacija_proto_rawDescOnce sync.Once
	file_replikacija_proto_rawDescData []byte
)

func file_replikacija_proto_rawDescGZIP() []byte {
	file_replikacija_proto_rawDescOnce.Do(func() {
		file_replikacija_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_replikacija_proto_rawDesc), len(file_replikacija_proto_rawDesc)))
	})
	return file_replikacija_proto_rawDescData
}

var file_replikacija_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_replikacija_proto_goTypes = []any{
	(*LogEntry)(nil),              // 0: replikacija.LogEntry
	(*ForwardRequest)(nil),        // 1: replikacija.ForwardRequest
	(*ForwardResponse)(nil),       // 2: replikacija.ForwardResponse
	(*CommitRequest)(nil),         // 3: replikacija.CommitRequest
	(*CommitResponse)(nil),        // 4: replikacija.CommitResponse
	(*UpdateRequest)(nil),         // 5: replikacija.UpdateRequest
	(*UpdateResponse)(nil),        // 6: replikacija.UpdateResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_replikacija_proto_depIdxs = []int32{
	7, // 0: replikacija.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: replikacija.ForwardRequest.entry:type_name -> replikacija.LogEntry
	0, // 2: replikacija.UpdateResponse.missing_entries:type_name -> replikacija.LogEntry
	1, // 3: replikacija.ReplicationService.Forward:input_type -> replikacija.ForwardRequest
	3, // 4: replikacija.ReplicationService.Commit:input_type -> replikacija.CommitRequest
	5, // 5: replikacija.ReplicationService.Update:input_type -> replikacija.UpdateRequest
	2, // 6: replikacija.ReplicationService.Forward:output_type -> replikacija.ForwardResponse
	4, // 7: replikacija.ReplicationService.Commit:output_type -> replikacija.CommitResponse
	6, // 8: replikacija.ReplicationService.Update:output_type -> replikacija.UpdateResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_replikacija_proto_init() }
func file_replikacija_proto_init() {
	if File_replikacija_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_replikacija_proto_rawDesc), len(file_replikacija_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_replikacija_proto_goTypes,
		DependencyIndexes: file_replikacija_proto_depIdxs,
		MessageInfos:      file_replikacija_proto_msgTypes,
	}.Build()
	File_replikacija_proto = out.File
	file_replikacija_proto_goTypes = nil
	file_replikacija_proto_depIdxs = nil
}
