// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: control.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	LeaderAddr    string                 `protobuf:"bytes,2,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"` // Naslov leaderja za redirect
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

// Raft peer management
type AddPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RaftAddr      string                 `protobuf:"bytes,2,opt,name=raft_addr,json=raftAddr,proto3" json:"raft_addr,omitempty"`
	GrpcAddr      string                 `protobuf:"bytes,3,opt,name=grpc_addr,json=grpcAddr,proto3" json:"grpc_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPeerRequest) Reset() {
	*x = AddPeerRequest{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPeerRequest) ProtoMessage() {}

func (x *AddPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPeerRequest.ProtoReflect.Descriptor instead.
func (*AddPeerRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *AddPeerRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AddPeerRequest) GetRaftAddr() string {
	if x != nil {
		return x.RaftAddr
	}
	return ""
}

func (x *AddPeerRequest) GetGrpcAddr() string {
	if x != nil {
		return x.GrpcAddr
	}
	return ""
}

type AddPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPeerResponse) Reset() {
	*x = AddPeerResponse{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPeerResponse) ProtoMessage() {}

func (x *AddPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPeerResponse.ProtoReflect.Descriptor instead.
func (*AddPeerResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *AddPeerResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AddPeerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RemovePeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePeerRequest) Reset() {
	*x = RemovePeerRequest{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePeerRequest) ProtoMessage() {}

func (x *RemovePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePeerRequest.ProtoReflect.Descriptor instead.
func (*RemovePeerRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *RemovePeerRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type RemovePeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePeerResponse) Reset() {
	*x = RemovePeerResponse{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePeerResponse) ProtoMessage() {}

func (x *RemovePeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePeerResponse.ProtoReflect.Descriptor instead.
func (*RemovePeerResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *RemovePeerResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RemovePeerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetRaftStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRaftStateRequest) Reset() {
	*x = GetRaftStateRequest{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRaftStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRaftStateRequest) ProtoMessage() {}

func (x *GetRaftStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRaftStateRequest.ProtoReflect.Descriptor instead.
func (*GetRaftStateRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

type GetRaftStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLeader      bool                   `protobuf:"varint,1,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaderAddr    string                 `protobuf:"bytes,3,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"`
	Peers         []*RaftPeer            `protobuf:"bytes,4,rep,name=peers,proto3" json:"peers,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"` // "leader", "follower", "candidate"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRaftStateResponse) Reset() {
	*x = GetRaftStateResponse{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRaftStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRaftStateResponse) ProtoMessage() {}

func (x *GetRaftStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRaftStateResponse.ProtoReflect.Descriptor instead.
func (*GetRaftStateResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *GetRaftStateResponse) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *GetRaftStateResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *GetRaftStateResponse) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

func (x *GetRaftStateResponse) GetPeers() []*RaftPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *GetRaftStateResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type RaftPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RaftAddr      string                 `protobuf:"bytes,2,opt,name=raft_addr,json=raftAddr,proto3" json:"raft_addr,omitempty"`
	GrpcAddr      string                 `protobuf:"bytes,3,opt,name=grpc_addr,json=grpcAddr,proto3" json:"grpc_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftPeer) Reset() {
	*x = RaftPeer{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftPeer) ProtoMessage() {}

func (x *RaftPeer) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftPeer.ProtoReflect.Descriptor instead.
func (*RaftPeer) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *RaftPeer) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RaftPeer) GetRaftAddr() string {
	if x != nil {
		return x.RaftAddr
	}
	return ""
}

func (x *RaftPeer) GetGrpcAddr() string {
	if x != nil {
		return x.GrpcAddr
	}
	return ""
}

type JoinChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeInfo              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinChainRequest) Reset() {
	*x = JoinChainRequest{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinChainRequest) ProtoMessage() {}

func (x *JoinChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinChainRequest.ProtoReflect.Descriptor instead.
func (*JoinChainRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

func (x *JoinChainRequest) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

type JoinChainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Previous      *NodeInfo              `protobuf:"bytes,1,opt,name=previous,proto3" json:"previous,omitempty"`                 // empty = head
	Next          *NodeInfo              `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`                         // empty = tail
	SyncFrom      *NodeInfo              `protobuf:"bytes,3,opt,name=sync_from,json=syncFrom,proto3" json:"sync_from,omitempty"` // koga prosimo za stvari (previous)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinChainResponse) Reset() {
	*x = JoinChainResponse{}
	mi := &file_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinChainResponse) ProtoMessage() {}

func (x *JoinChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinChainResponse.ProtoReflect.Descriptor instead.
func (*JoinChainResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{11}
}

func (x *JoinChainResponse) GetPrevious() *NodeInfo {
	if x != nil {
		return x.Previous
	}
	return nil
}

func (x *JoinChainResponse) GetNext() *NodeInfo {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *JoinChainResponse) GetSyncFrom() *NodeInfo {
	if x != nil {
		return x.SyncFrom
	}
	return nil
}

type UpdateNeighborsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Self          *NodeInfo              `protobuf:"bytes,1,opt,name=self,proto3" json:"self,omitempty"`
	Previous      *NodeInfo              `protobuf:"bytes,2,opt,name=previous,proto3" json:"previous,omitempty"` // empty = head
	Next          *NodeInfo              `protobuf:"bytes,3,opt,name=next,proto3" json:"next,omitempty"`         // empty = tail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNeighborsRequest) Reset() {
	*x = UpdateNeighborsRequest{}
	mi := &file_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNeighborsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNeighborsRequest) ProtoMessage() {}

func (x *UpdateNeighborsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNeighborsRequest.ProtoReflect.Descriptor instead.
func (*UpdateNeighborsRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateNeighborsRequest) GetSelf() *NodeInfo {
	if x != nil {
		return x.Self
	}
	return nil
}

func (x *UpdateNeighborsRequest) GetPrevious() *NodeInfo {
	if x != nil {
		return x.Previous
	}
	return nil
}

func (x *UpdateNeighborsRequest) GetNext() *NodeInfo {
	if x != nil {
		return x.Next
	}
	return nil
}

type UpdateNeighborsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNeighborsResponse) Reset() {
	*x = UpdateNeighborsResponse{}
	mi := &file_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNeighborsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNeighborsResponse) ProtoMessage() {}

func (x *UpdateNeighborsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNeighborsResponse.ProtoReflect.Descriptor instead.
func (*UpdateNeighborsResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateNeighborsResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChainRequest) Reset() {
	*x = GetChainRequest{}
	mi := &file_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChainRequest) ProtoMessage() {}

func (x *GetChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChainRequest.ProtoReflect.Descriptor instead.
func (*GetChainRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{14}
}

type GetChainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         []*NodeInfo            `protobuf:"bytes,1,rep,name=chain,proto3" json:"chain,omitempty"`
	Head          *NodeInfo              `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`
	Tail          *NodeInfo              `protobuf:"bytes,3,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChainResponse) Reset() {
	*x = GetChainResponse{}
	mi := &file_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChainResponse) ProtoMessage() {}

func (x *GetChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChainResponse.ProtoReflect.Descriptor instead.
func (*GetChainResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{15}
}

func (x *GetChainResponse) GetChain() []*NodeInfo {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *GetChainResponse) GetHead() *NodeInfo {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *GetChainResponse) GetTail() *NodeInfo {
	if x != nil {
		return x.Tail
	}
	return nil
}

// Notifikacija data node-om, da se je leader spremenil
type NotifyLeaderChangeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LeaderId        string                 `protobuf:"bytes,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaderGrpcAddr  string                 `protobuf:"bytes,2,opt,name=leader_grpc_addr,json=leaderGrpcAddr,proto3" json:"leader_grpc_addr,omitempty"`    // gRPC naslov novega leaderja
	AllControlAddrs []string               `protobuf:"bytes,3,rep,name=all_control_addrs,json=allControlAddrs,proto3" json:"all_control_addrs,omitempty"` // Vsi control unit naslovi za failover
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NotifyLeaderChangeRequest) Reset() {
	*x = NotifyLeaderChangeRequest{}
	mi := &file_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyLeaderChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyLeaderChangeRequest) ProtoMessage() {}

func (x *NotifyLeaderChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyLeaderChangeRequest.ProtoReflect.Descriptor instead.
func (*NotifyLeaderChangeRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{16}
}

func (x *NotifyLeaderChangeRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *NotifyLeaderChangeRequest) GetLeaderGrpcAddr() string {
	if x != nil {
		return x.LeaderGrpcAddr
	}
	return ""
}

func (x *NotifyLeaderChangeRequest) GetAllControlAddrs() []string {
	if x != nil {
		return x.AllControlAddrs
	}
	return nil
}

type NotifyLeaderChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyLeaderChangeResponse) Reset() {
	*x = NotifyLeaderChangeResponse{}
	mi := &file_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyLeaderChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyLeaderChangeResponse) ProtoMessage() {}

func (x *NotifyLeaderChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyLeaderChangeResponse.ProtoReflect.Descriptor instead.
func (*NotifyLeaderChangeResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{17}
}

func (x *NotifyLeaderChangeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\fcontrolplane\"=\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"+\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"D\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1f\n" +
	"\vleader_addr\x18\x02 \x01(\tR\n" +
	"leaderAddr\"c\n" +
	"\x0eAddPeerRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\traft_addr\x18\x02 \x01(\tR\braftAddr\x12\x1b\n" +
	"\tgrpc_addr\x18\x03 \x01(\tR\bgrpcAddr\"7\n" +
	"\x0fAddPeerResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\",\n" +
	"\x11RemovePeerRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\":\n" +
	"\x12RemovePeerResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x15\n" +
	"\x13GetRaftStateRequest\"\xb5\x01\n" +
	"\x14GetRaftStateResponse\x12\x1b\n" +
	"\tis_leader\x18\x01 \x01(\bR\bisLeader\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x12\x1f\n" +
	"\vleader_addr\x18\x03 \x01(\tR\n" +
	"leaderAddr\x12,\n" +
	"\x05peers\x18\x04 \x03(\v2\x16.controlplane.RaftPeerR\x05peers\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\"]\n" +
	"\bRaftPeer\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\traft_addr\x18\x02 \x01(\tR\braftAddr\x12\x1b\n" +
	"\tgrpc_addr\x18\x03 \x01(\tR\bgrpcAddr\">\n" +
	"\x10JoinChainRequest\x12*\n" +
	"\x04node\x18\x01 \x01(\v2\x16.controlplane.NodeInfoR\x04node\"\xa8\x01\n" +
	"\x11JoinChainResponse\x122\n" +
	"\bprevious\x18\x01 \x01(\v2\x16.controlplane.NodeInfoR\bprevious\x12*\n" +
	"\x04next\x18\x02 \x01(\v2\x16.controlplane.NodeInfoR\x04next\x123\n" +
	"\tsync_from\x18\x03 \x01(\v2\x16.controlplane.NodeInfoR\bsyncFrom\"\xa4\x01\n" +
	"\x16UpdateNeighborsRequest\x12*\n" +
	"\x04self\x18\x01 \x01(\v2\x16.controlplane.NodeInfoR\x04self\x122\n" +
	"\bprevious\x18\x02 \x01(\v2\x16.controlplane.NodeInfoR\bprevious\x12*\n" +
	"\x04next\x18\x03 \x01(\v2\x16.controlplane.NodeInfoR\x04next\")\n" +
	"\x17UpdateNeighborsResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x11\n" +
	"\x0fGetChainRequest\"\x98\x01\n" +
	"\x10GetChainResponse\x12,\n" +
	"\x05chain\x18\x01 \x03(\v2\x16.controlplane.NodeInfoR\x05chain\x12*\n" +
	"\x04head\x18\x02 \x01(\v2\x16.controlplane.NodeInfoR\x04head\x12*\n" +
	"\x04tail\x18\x03 \x01(\v2\x16.controlplane.NodeInfoR\x04tail\"\x8e\x01\n" +
	"\x19NotifyLeaderChangeRequest\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\tR\bleaderId\x12(\n" +
	"\x10leader_grpc_addr\x18\x02 \x01(\tR\x0eleaderGrpcAddr\x12*\n" +
	"\x11all_control_addrs\x18\x03 \x03(\tR\x0fallControlAddrs\",\n" +
	"\x1aNotifyLeaderChangeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xb5\x05\n" +
	"\x13ControlPlaneService\x12L\n" +
	"\tHeartbeat\x12\x1e.controlplane.HeartbeatRequest\x1a\x1f.controlplane.HeartbeatResponse\x12L\n" +
	"\tJoinChain\x12\x1e.controlplane.JoinChainRequest\x1a\x1f.controlplane.JoinChainResponse\x12^\n" +
	"\x0fUpdateNeighbors\x12$.controlplane.UpdateNeighborsRequest\x1a%.controlplane.UpdateNeighborsResponse\x12I\n" +
	"\bGetChain\x12\x1d.controlplane.GetChainRequest\x1a\x1e.controlplane.GetChainResponse\x12F\n" +
	"\aAddPeer\x12\x1c.controlplane.AddPeerRequest\x1a\x1d.controlplane.AddPeerResponse\x12O\n" +
	"\n" +
	"RemovePeer\x12\x1f.controlplane.RemovePeerRequest\x1a .controlplane.RemovePeerResponse\x12U\n" +
	"\fGetRaftState\x12!.controlplane.GetRaftStateRequest\x1a\".controlplane.GetRaftStateResponse\x12g\n" +
	"\x12NotifyLeaderChange\x12'.controlplane.NotifyLeaderChangeRequest\x1a(.controlplane.NotifyLeaderChangeResponseB8Z6github.com/FedjaMocnik/razpravljalnica/pkgs/control/pbb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_control_proto_goTypes = []any{
	(*NodeInfo)(nil),                   // 0: controlplane.NodeInfo
	(*HeartbeatRequest)(nil),           // 1: controlplane.HeartbeatRequest
	(*HeartbeatResponse)(nil),          // 2: controlplane.HeartbeatResponse
	(*AddPeerRequest)(nil),             // 3: controlplane.AddPeerRequest
	(*AddPeerResponse)(nil),            // 4: controlplane.AddPeerResponse
	(*RemovePeerRequest)(nil),          // 5: controlplane.RemovePeerRequest
	(*RemovePeerResponse)(nil),         // 6: controlplane.RemovePeerResponse
	(*GetRaftStateRequest)(nil),        // 7: controlplane.GetRaftStateRequest
	(*GetRaftStateResponse)(nil),       // 8: controlplane.GetRaftStateResponse
	(*RaftPeer)(nil),                   // 9: controlplane.RaftPeer
	(*JoinChainRequest)(nil),           // 10: controlplane.JoinChainRequest
	(*JoinChainResponse)(nil),          // 11: controlplane.JoinChainResponse
	(*UpdateNeighborsRequest)(nil),     // 12: controlplane.UpdateNeighborsRequest
	(*UpdateNeighborsResponse)(nil),    // 13: controlplane.UpdateNeighborsResponse
	(*GetChainRequest)(nil),            // 14: controlplane.GetChainRequest
	(*GetChainResponse)(nil),           // 15: controlplane.GetChainResponse
	(*NotifyLeaderChangeRequest)(nil),  // 16: controlplane.NotifyLeaderChangeRequest
	(*NotifyLeaderChangeResponse)(nil), // 17: controlplane.NotifyLeaderChangeResponse
}
var file_control_proto_depIdxs = []int32{
	9,  // 0: controlplane.GetRaftStateResponse.peers:type_name -> controlplane.RaftPeer
	0,  // 1: controlplane.JoinChainRequest.node:type_name -> controlplane.NodeInfo
	0,  // 2: controlplane.JoinChainResponse.previous:type_name -> controlplane.NodeInfo
	0,  // 3: controlplane.JoinChainResponse.next:type_name -> controlplane.NodeInfo
	0,  // 4: controlplane.JoinChainResponse.sync_from:type_name -> controlplane.NodeInfo
	0,  // 5: controlplane.UpdateNeighborsRequest.self:type_name -> controlplane.NodeInfo
	0,  // 6: controlplane.UpdateNeighborsRequest.previous:type_name -> controlplane.NodeInfo
	0,  // 7: controlplane.UpdateNeighborsRequest.next:type_name -> controlplane.NodeInfo
	0,  // 8: controlplane.GetChainResponse.chain:type_name -> controlplane.NodeInfo
	0,  // 9: controlplane.GetChainResponse.head:type_name -> controlplane.NodeInfo
	0,  // 10: controlplane.GetChainResponse.tail:type_name -> controlplane.NodeInfo
	1,  // 11: controlplane.ControlPlaneService.Heartbeat:input_type -> controlplane.HeartbeatRequest
	10, // 12: controlplane.ControlPlaneService.JoinChain:input_type -> controlplane.JoinChainRequest
	12, // 13: controlplane.ControlPlaneService.UpdateNeighbors:input_type -> controlplane.UpdateNeighborsRequest
	14, // 14: controlplane.ControlPlaneService.GetChain:input_type -> controlplane.GetChainRequest
	3,  // 15: controlplane.ControlPlaneService.AddPeer:input_type -> controlplane.AddPeerRequest
	5,  // 16: controlplane.ControlPlaneService.RemovePeer:input_type -> controlplane.RemovePeerRequest
	7,  // 17: controlplane.ControlPlaneService.GetRaftState:input_type -> controlplane.GetRaftStateRequest
	16, // 18: controlplane.ControlPlaneService.NotifyLeaderChange:input_type -> controlplane.NotifyLeaderChangeRequest
	2,  // 19: controlplane.ControlPlaneService.Heartbeat:output_type -> controlplane.HeartbeatResponse
	11, // 20: controlplane.ControlPlaneService.JoinChain:output_type -> controlplane.JoinChainResponse
	13, // 21: controlplane.ControlPlaneService.UpdateNeighbors:output_type -> controlplane.UpdateNeighborsResponse
	15, // 22: controlplane.ControlPlaneService.GetChain:output_type -> controlplane.GetChainResponse
	4,  // 23: controlplane.ControlPlaneService.AddPeer:output_type -> controlplane.AddPeerResponse
	6,  // 24: controlplane.ControlPlaneService.RemovePeer:output_type -> controlplane.RemovePeerResponse
	8,  // 25: controlplane.ControlPlaneService.GetRaftState:output_type -> controlplane.GetRaftStateResponse
	17, // 26: controlplane.ControlPlaneService.NotifyLeaderChange:output_type -> controlplane.NotifyLeaderChangeResponse
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
