// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: control.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type JoinChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeInfo              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinChainRequest) Reset() {
	*x = JoinChainRequest{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinChainRequest) ProtoMessage() {}

func (x *JoinChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinChainRequest.ProtoReflect.Descriptor instead.
func (*JoinChainRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *JoinChainRequest) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

type JoinChainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Previous      *NodeInfo              `protobuf:"bytes,1,opt,name=previous,proto3" json:"previous,omitempty"`                 // empty = head
	Next          *NodeInfo              `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`                         // empty = tail
	SyncFrom      *NodeInfo              `protobuf:"bytes,3,opt,name=sync_from,json=syncFrom,proto3" json:"sync_from,omitempty"` // koga prosimo za stvari (previous)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinChainResponse) Reset() {
	*x = JoinChainResponse{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinChainResponse) ProtoMessage() {}

func (x *JoinChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinChainResponse.ProtoReflect.Descriptor instead.
func (*JoinChainResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *JoinChainResponse) GetPrevious() *NodeInfo {
	if x != nil {
		return x.Previous
	}
	return nil
}

func (x *JoinChainResponse) GetNext() *NodeInfo {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *JoinChainResponse) GetSyncFrom() *NodeInfo {
	if x != nil {
		return x.SyncFrom
	}
	return nil
}

type UpdateNeighborsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Self          *NodeInfo              `protobuf:"bytes,1,opt,name=self,proto3" json:"self,omitempty"`
	Previous      *NodeInfo              `protobuf:"bytes,2,opt,name=previous,proto3" json:"previous,omitempty"` // empty = head
	Next          *NodeInfo              `protobuf:"bytes,3,opt,name=next,proto3" json:"next,omitempty"`         // empty = tail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNeighborsRequest) Reset() {
	*x = UpdateNeighborsRequest{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNeighborsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNeighborsRequest) ProtoMessage() {}

func (x *UpdateNeighborsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNeighborsRequest.ProtoReflect.Descriptor instead.
func (*UpdateNeighborsRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateNeighborsRequest) GetSelf() *NodeInfo {
	if x != nil {
		return x.Self
	}
	return nil
}

func (x *UpdateNeighborsRequest) GetPrevious() *NodeInfo {
	if x != nil {
		return x.Previous
	}
	return nil
}

func (x *UpdateNeighborsRequest) GetNext() *NodeInfo {
	if x != nil {
		return x.Next
	}
	return nil
}

type UpdateNeighborsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNeighborsResponse) Reset() {
	*x = UpdateNeighborsResponse{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNeighborsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNeighborsResponse) ProtoMessage() {}

func (x *UpdateNeighborsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNeighborsResponse.ProtoReflect.Descriptor instead.
func (*UpdateNeighborsResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateNeighborsResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChainRequest) Reset() {
	*x = GetChainRequest{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChainRequest) ProtoMessage() {}

func (x *GetChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChainRequest.ProtoReflect.Descriptor instead.
func (*GetChainRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

type GetChainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         []*NodeInfo            `protobuf:"bytes,1,rep,name=chain,proto3" json:"chain,omitempty"`
	Head          *NodeInfo              `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`
	Tail          *NodeInfo              `protobuf:"bytes,3,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChainResponse) Reset() {
	*x = GetChainResponse{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChainResponse) ProtoMessage() {}

func (x *GetChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChainResponse.ProtoReflect.Descriptor instead.
func (*GetChainResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *GetChainResponse) GetChain() []*NodeInfo {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *GetChainResponse) GetHead() *NodeInfo {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *GetChainResponse) GetTail() *NodeInfo {
	if x != nil {
		return x.Tail
	}
	return nil
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\fcontrolplane\"=\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"+\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"#\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\">\n" +
	"\x10JoinChainRequest\x12*\n" +
	"\x04node\x18\x01 \x01(\v2\x16.controlplane.NodeInfoR\x04node\"\xa8\x01\n" +
	"\x11JoinChainResponse\x122\n" +
	"\bprevious\x18\x01 \x01(\v2\x16.controlplane.NodeInfoR\bprevious\x12*\n" +
	"\x04next\x18\x02 \x01(\v2\x16.controlplane.NodeInfoR\x04next\x123\n" +
	"\tsync_from\x18\x03 \x01(\v2\x16.controlplane.NodeInfoR\bsyncFrom\"\xa4\x01\n" +
	"\x16UpdateNeighborsRequest\x12*\n" +
	"\x04self\x18\x01 \x01(\v2\x16.controlplane.NodeInfoR\x04self\x122\n" +
	"\bprevious\x18\x02 \x01(\v2\x16.controlplane.NodeInfoR\bprevious\x12*\n" +
	"\x04next\x18\x03 \x01(\v2\x16.controlplane.NodeInfoR\x04next\")\n" +
	"\x17UpdateNeighborsResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x11\n" +
	"\x0fGetChainRequest\"\x98\x01\n" +
	"\x10GetChainResponse\x12,\n" +
	"\x05chain\x18\x01 \x03(\v2\x16.controlplane.NodeInfoR\x05chain\x12*\n" +
	"\x04head\x18\x02 \x01(\v2\x16.controlplane.NodeInfoR\x04head\x12*\n" +
	"\x04tail\x18\x03 \x01(\v2\x16.controlplane.NodeInfoR\x04tail2\xdc\x02\n" +
	"\x13ControlPlaneService\x12L\n" +
	"\tHeartbeat\x12\x1e.controlplane.HeartbeatRequest\x1a\x1f.controlplane.HeartbeatResponse\x12L\n" +
	"\tJoinChain\x12\x1e.controlplane.JoinChainRequest\x1a\x1f.controlplane.JoinChainResponse\x12^\n" +
	"\x0fUpdateNeighbors\x12$.controlplane.UpdateNeighborsRequest\x1a%.controlplane.UpdateNeighborsResponse\x12I\n" +
	"\bGetChain\x12\x1d.controlplane.GetChainRequest\x1a\x1e.controlplane.GetChainResponseB8Z6github.com/FedjaMocnik/razpravljalnica/pkgs/control/pbb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_control_proto_goTypes = []any{
	(*NodeInfo)(nil),                // 0: controlplane.NodeInfo
	(*HeartbeatRequest)(nil),        // 1: controlplane.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 2: controlplane.HeartbeatResponse
	(*JoinChainRequest)(nil),        // 3: controlplane.JoinChainRequest
	(*JoinChainResponse)(nil),       // 4: controlplane.JoinChainResponse
	(*UpdateNeighborsRequest)(nil),  // 5: controlplane.UpdateNeighborsRequest
	(*UpdateNeighborsResponse)(nil), // 6: controlplane.UpdateNeighborsResponse
	(*GetChainRequest)(nil),         // 7: controlplane.GetChainRequest
	(*GetChainResponse)(nil),        // 8: controlplane.GetChainResponse
}
var file_control_proto_depIdxs = []int32{
	0,  // 0: controlplane.JoinChainRequest.node:type_name -> controlplane.NodeInfo
	0,  // 1: controlplane.JoinChainResponse.previous:type_name -> controlplane.NodeInfo
	0,  // 2: controlplane.JoinChainResponse.next:type_name -> controlplane.NodeInfo
	0,  // 3: controlplane.JoinChainResponse.sync_from:type_name -> controlplane.NodeInfo
	0,  // 4: controlplane.UpdateNeighborsRequest.self:type_name -> controlplane.NodeInfo
	0,  // 5: controlplane.UpdateNeighborsRequest.previous:type_name -> controlplane.NodeInfo
	0,  // 6: controlplane.UpdateNeighborsRequest.next:type_name -> controlplane.NodeInfo
	0,  // 7: controlplane.GetChainResponse.chain:type_name -> controlplane.NodeInfo
	0,  // 8: controlplane.GetChainResponse.head:type_name -> controlplane.NodeInfo
	0,  // 9: controlplane.GetChainResponse.tail:type_name -> controlplane.NodeInfo
	1,  // 10: controlplane.ControlPlaneService.Heartbeat:input_type -> controlplane.HeartbeatRequest
	3,  // 11: controlplane.ControlPlaneService.JoinChain:input_type -> controlplane.JoinChainRequest
	5,  // 12: controlplane.ControlPlaneService.UpdateNeighbors:input_type -> controlplane.UpdateNeighborsRequest
	7,  // 13: controlplane.ControlPlaneService.GetChain:input_type -> controlplane.GetChainRequest
	2,  // 14: controlplane.ControlPlaneService.Heartbeat:output_type -> controlplane.HeartbeatResponse
	4,  // 15: controlplane.ControlPlaneService.JoinChain:output_type -> controlplane.JoinChainResponse
	6,  // 16: controlplane.ControlPlaneService.UpdateNeighbors:output_type -> controlplane.UpdateNeighborsResponse
	8,  // 17: controlplane.ControlPlaneService.GetChain:output_type -> controlplane.GetChainResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
