// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: control.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlaneService_Heartbeat_FullMethodName       = "/controlplane.ControlPlaneService/Heartbeat"
	ControlPlaneService_JoinChain_FullMethodName       = "/controlplane.ControlPlaneService/JoinChain"
	ControlPlaneService_UpdateNeighbors_FullMethodName = "/controlplane.ControlPlaneService/UpdateNeighbors"
	ControlPlaneService_GetChain_FullMethodName        = "/controlplane.ControlPlaneService/GetChain"
)

// ControlPlaneServiceClient is the client API for ControlPlaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlPlaneServiceClient interface {
	// Periodični Heartbeat.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Torej spremebe chaina: Server se mu pridruži ali zapusti.
	JoinChain(ctx context.Context, in *JoinChainRequest, opts ...grpc.CallOption) (*JoinChainResponse, error)
	// Pošljemo serverju nove sosede.
	UpdateNeighbors(ctx context.Context, in *UpdateNeighborsRequest, opts ...grpc.CallOption) (*UpdateNeighborsResponse, error)
	// torej ker control ve nek chain je to ubistvu request, če ga še kdo potrebuje.
	GetChain(ctx context.Context, in *GetChainRequest, opts ...grpc.CallOption) (*GetChainResponse, error)
}

type controlPlaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneServiceClient(cc grpc.ClientConnInterface) ControlPlaneServiceClient {
	return &controlPlaneServiceClient{cc}
}

func (c *controlPlaneServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) JoinChain(ctx context.Context, in *JoinChainRequest, opts ...grpc.CallOption) (*JoinChainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinChainResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_JoinChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) UpdateNeighbors(ctx context.Context, in *UpdateNeighborsRequest, opts ...grpc.CallOption) (*UpdateNeighborsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNeighborsResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_UpdateNeighbors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) GetChain(ctx context.Context, in *GetChainRequest, opts ...grpc.CallOption) (*GetChainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChainResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServiceServer is the server API for ControlPlaneService service.
// All implementations must embed UnimplementedControlPlaneServiceServer
// for forward compatibility.
type ControlPlaneServiceServer interface {
	// Periodični Heartbeat.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Torej spremebe chaina: Server se mu pridruži ali zapusti.
	JoinChain(context.Context, *JoinChainRequest) (*JoinChainResponse, error)
	// Pošljemo serverju nove sosede.
	UpdateNeighbors(context.Context, *UpdateNeighborsRequest) (*UpdateNeighborsResponse, error)
	// torej ker control ve nek chain je to ubistvu request, če ga še kdo potrebuje.
	GetChain(context.Context, *GetChainRequest) (*GetChainResponse, error)
	mustEmbedUnimplementedControlPlaneServiceServer()
}

// UnimplementedControlPlaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServiceServer struct{}

func (UnimplementedControlPlaneServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedControlPlaneServiceServer) JoinChain(context.Context, *JoinChainRequest) (*JoinChainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinChain not implemented")
}
func (UnimplementedControlPlaneServiceServer) UpdateNeighbors(context.Context, *UpdateNeighborsRequest) (*UpdateNeighborsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNeighbors not implemented")
}
func (UnimplementedControlPlaneServiceServer) GetChain(context.Context, *GetChainRequest) (*GetChainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChain not implemented")
}
func (UnimplementedControlPlaneServiceServer) mustEmbedUnimplementedControlPlaneServiceServer() {}
func (UnimplementedControlPlaneServiceServer) testEmbeddedByValue()                             {}

// UnsafeControlPlaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServiceServer will
// result in compilation errors.
type UnsafeControlPlaneServiceServer interface {
	mustEmbedUnimplementedControlPlaneServiceServer()
}

func RegisterControlPlaneServiceServer(s grpc.ServiceRegistrar, srv ControlPlaneServiceServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlaneService_ServiceDesc, srv)
}

func _ControlPlaneService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_JoinChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).JoinChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_JoinChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).JoinChain(ctx, req.(*JoinChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_UpdateNeighbors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNeighborsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).UpdateNeighbors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_UpdateNeighbors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).UpdateNeighbors(ctx, req.(*UpdateNeighborsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_GetChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetChain(ctx, req.(*GetChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlaneService_ServiceDesc is the grpc.ServiceDesc for ControlPlaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "controlplane.ControlPlaneService",
	HandlerType: (*ControlPlaneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _ControlPlaneService_Heartbeat_Handler,
		},
		{
			MethodName: "JoinChain",
			Handler:    _ControlPlaneService_JoinChain_Handler,
		},
		{
			MethodName: "UpdateNeighbors",
			Handler:    _ControlPlaneService_UpdateNeighbors_Handler,
		},
		{
			MethodName: "GetChain",
			Handler:    _ControlPlaneService_GetChain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control.proto",
}
